app = "pocket-demon-ultimate"
primary_region = "lon"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["python"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

[env]
  TELEGRAM_BOT_TOKEN = ""
