services:
  - type: web
    name: pocket-demon
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --only-binary=:all: -r requirements.txt || \
      pip install --only-binary=pandas,numpy,matplotlib,scikit-learn -r requirements.txt
    startCommand: python po_demon.py
    plan: free
    autoDeploy: true
    envVars:
      TELEGRAM_BOT_TOKEN:
        fromSecret: TELEGRAM_BOT_TOKEN
