services:
  - type: web
    name: pocket-demon-ultimate
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --only-binary=:all: -r requirements.txt
    startCommand: python po_demon.py
    plan: free
    autoDeploy: true
    envVars:
      TELEGRAM_BOT_TOKEN:
        fromSecret: TELEGRAM_BOT_TOKEN
